### ISSUE TITLE
Ignoring pool size config

### ISSUE THREAD

**Issue by starkovv** [jhollinger/grape-activerecord#3]
ActiveRecord config loader:
```
Grape::ActiveRecord.database_file = File.join(__dir__, '..', 'config', 'database.yml')
```

database.yml:
```
development:
  adapter: postgresql
  host: 192.168.7.16
  encoding: unicode
  username: postgres
  password: secret
  database: app_development
  pool: 10

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  host: 192.168.7.16
  encoding: unicode
  username: postgres
  password: secret
  database: app_test
  pool: 10

production:
  adapter: postgresql
  host: 192.168.7.16
  encoding: unicode
  username: postgres
  password: secret
  database: app_production
  pool: 10
```

Then when I test it with:
```
ab -c 10 -n 1000 http://192.168.7.10/users
```

It opens exactly 20 connections to PostgreSQL:
```
tcp        0    139 192.168.7.16:postgresql 192.168.7.10:39666    ESTABLISHED
tcp        0      0 192.168.7.16:postgresql 192.168.7.10:39658    ESTABLISHED
tcp        0      0 192.168.7.16:postgresql 192.168.7.10:39664    ESTABLISHED
tcp        0      0 192.168.7.16:postgresql 192.168.7.10:39662    ESTABLISHED
...
```

The same if I make `pool: 2` or `pool: 70`.

**Comment by starkovv** [comment]
Additionally.

The same thing if I set configuration directly:
```
Grape::ActiveRecord.database = {
  adapter:  'postgresql'
  host:     '192.168.7.16'
  encoding: 'utf8'
  username: 'postgres'
  password: 'secret'
  database: 'app_development'
  pool: 7
}
```

It, as I said before, ignores `pool:` parameter and keep 20 connections open permanently. Initially it doesn't open _any_ connection on application initialization. Only when first request to DB was made, it opens first connection. On second request it opens second connection. And go this way up until it reach 20 connections established.

**Comment by jhollinger** [comment]
What versions of activerecord and grape-activerecord are you running? What is value of `ActiveRecord::Base.connection.pool.size`?

**Comment by starkovv** [comment]
@jhollinger `ActiveRecord::Base.connection.pool.size` has value of `5`.

Ruby version: `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]`.

Gems:
```
grape-activerecord (0.0.8)
activerecord (~> 4.0)
grape (~> 0.1)
hashie-forbidden_attributes (~> 0.1.1)
```

**Comment by jhollinger** [comment]
Right, but I mean if you set it to 7, does `ActiveRecord::Base.connection.pool.size` actually equal 7 when the app is running?

**Comment by starkovv** [comment]
Yepp.

In both cases (with database.yml and with direct configuration) `ActiveRecord::Base.connection.pool.size` equals `7`.

Side-note:
After quite long period of inactivity, the number of connections to DB decreases down to 1.

**Comment by starkovv** [comment]
It looks like `grape-activerecord` does not pass pool config into `active_record`.

OR

It may be an issue in ActiveRecord itself.

**Comment by jhollinger** [comment]
From what I can tell using AR 4.2, the pool size in `ActiveRecord::Base.connection.pool.size` respects whatever is in `database.yml`. Feel free to re-open if new info is available.
