### ISSUE TITLE
include Grape::ActiveRecord::Extension throws error

### ISSUE THREAD

**Issue by rjayroach** [jhollinger/grape-activerecord#4]
Hi, Thanks for writing this gem. I've come across this issue:

Using grape-activerecord 0.0.8
Using activerecord 4.2.3

When I follow the README and `include Grape::ActiveRecord::Extension` in my Grape API class I get the following error:
```
undefined method 'downcase' for 2:Fixnum

Ruby	/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/utils.rb: in [], line 501
```

Looking into that code there are just these two lines:
```
Grape::ActiveRecord.setup!
app.use ::ActiveRecord::ConnectionAdapters::ConnectionManagement
```

When I remove the `include Grape::ActiveRecord::Extension` from the API class and replace it with just `Grape::ActiveRecord.setup!` it works fine.

Following your README I have put in config.ru `use ActiveRecord::ConnectionAdapters::ConnectionManagement`

I played around with removing the use from config.ru since it seems redundant when including the mixin, but that didn't remove the error. any idea?

**Comment by jhollinger** [comment]
It looks like an incompatibility between grape 0.12 and `ActiveRecord::ConnectionAdapters::ConnectionManagement`. As a result you can't `use` it inside of the grape app anymore - you have to use it outside, like in your `config.ru`. Can you help me confirm that the following setup works?

* Remove `include Grape::ActiveRecord::Extension`
* Put `use ActiveRecord::ConnectionAdapters::ConnectionManagement` in `config.ru`
* Put `Grape::ActiveRecord.setup!` somewhere (config.ru, above your API class, anywhere really)

If that works for now, I'll work on updating the docs and/or finding a better way to load things in the next version. Alternatively, you can downgrade to grape 0.11.

**Comment by jhollinger** [comment]
1.0.0 is out and should fix this. Just take a look at the new README - should be simpler.
